#!/bin/sh

# use the django manage.py command from within a docker container from shell on host

ARGS="$@"

docker compose exec flask-api-local sh -c "cd /code/applications/flask-api && poetry $ARGS"
