"""
add models

Revision ID: 05fa0ae3869e
Revises: 
Create Date: 2021-08-02 21:07:17.438624
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fa0ae3869e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('vin', sa.String(length=40), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fillup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('gallons', sa.Float(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fillup')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
